hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task: []
  job:
    name: main
    chdir: null
    override_dirname: ''
    id: ???
    num: ???
    config_name: hydra-config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.1'
    cwd: /home/hshayde/Projects/MIT/AMR
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/hshayde/Projects/MIT/AMR/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
project_name: Testing_Transformer
run_name: Tokenized_AMR:${now:%Y-%m-%d_%H-%M-%S}
train_tokenizer: false
mode: online
debug: false
log_model: true
seed: 42
hyperparams:
  epochs: 10
  learning_rate: 0.001
  batch_size: 32
  dropout: 0.25
  hidden_dim: 64
  feature_dim: 32
  num_classes: 11
output_dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
data_dir: data/
Tokenizer:
  _target_: models.vq_vae.vq_vae.RFVQVAE
  commitment_cost: 0.25
  learning_rate: 0.001
  quantizer_amp:
    _target_: models.vq_vae.quantizer.VectorQuantizerEMA
    embedding_dim: 64
    codebook_size: 512
    beta: 0.25
    decay: 0.99
    epsilon: 1.0e-05
  quantizer_phase:
    _target_: models.vq_vae.quantizer.VectorQuantizerEMA
    embedding_dim: 64
    codebook_size: 512
    beta: 0.25
    decay: 0.99
    epsilon: 1.0e-05
  encoder_amp:
    _target_: models.vq_vae.encoder.Encoder
    hidden_dim: 128
    feature_dim: 64
  encoder_phase:
    _target_: models.vq_vae.encoder.Encoder
    hidden_dim: 128
    feature_dim: 64
  decoder_amp:
    _target_: models.vq_vae.decoder.Decoder
    embedding_dim: ${Tokenizer.quantizer_amp.embedding_dim}
    feature_dim: ${Tokenizer.encoder_amp.feature_dim}
    output_channels: 1
    output_dim: 128
  decoder_phase:
    _target_: models.vq_vae.decoder.Decoder
    embedding_dim: ${Tokenizer.quantizer_phase.embedding_dim}
    feature_dim: ${Tokenizer.encoder_phase.feature_dim}
    output_channels: 1
    output_dim: 128
Transformer:
  _target_: models.experts.attention.transformer_module.BidirectionalTransformer
  epochs: ${hyperparams.epochs}
  embed_dim: ${Tokenizer.quantizer_amp.embedding_dim}
  num_heads: 8
  num_layers: 6
  dropout: 0.2
  num_classes: ${hyperparams.num_classes}
  learning_rate: ${hyperparams.learning_rate}
Model:
  _target_: models.router.Router
  input_dim: 256
  hidden_dim: ${hyperparams.hidden_dim}
  feature_dim: ${hyperparams.feature_dim}
  lr: ${hyperparams.learning_rate}
  num_classes: ${hyperparams.num_classes}
  load_balance_experts: false
  experts: null
  classifier:
    _target_: models.classifier.Classifier
    input_dim: ${hyperparams.feature_dim}
    hidden_dim: ${hyperparams.hidden_dim}
    num_classes: ${hyperparams.num_classes}
    dropout: ${hyperparams.dropout}
dataset:
  iq: false
  batch_size: ${hyperparams.batch_size}
  num_workers: 4
  train_val_split:
  - 0.7
  - 0.3
  random_seed: ${seed}
