program: src/main.py
method: bayes
metric:
  name: val_acc
  goal: maximize
parameters:
  hyperparams.learning_rate:
    distribution: uniform
    min: 0.00005
    max: 0.001
  hyperparams.batch_size:
    values: [32, 64, 128]
  Transformer.dropout:
    distribution: uniform
    min: 0.1
    max: 0.5
  Transformer.num_heads:
    values: [2, 4, 8]
  Transformer.num_layers:
    values: [2, 4, 6, 8]

command:
  - ${env}
  - python
  - ${program}
  - --multirun # allows hydra to accept multiple runs for sweeps
