program: src/main.py
name: testing_timesteps
method: grid
metric:
    name: val/class_loss
    goal: minimize
parameters:
    Encoder.num_train_timesteps:
        values: [1, 5, 10, 20]

command:
    - ${env}
    - python
    - ${program}
    - --multirun # allows hydra to accept multiple runs for sweeps
